// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_tech_task/test/test_helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_tech_task/data/models/post_model.dart' as _i5;
import 'package:flutter_tech_task/usecases/save_post_usecase.dart' as _i2;
import 'package:flutter_tech_task/utils/result.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SavePostUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSavePostUseCase extends _i1.Mock implements _i2.SavePostUseCase {
  @override
  _i3.Future<_i4.Result<bool>> savePostAndComments({required _i5.Post? post}) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePostAndComments,
          [],
          {#post: post},
        ),
        returnValue:
            _i3.Future<_i4.Result<bool>>.value(_i6.dummyValue<_i4.Result<bool>>(
          this,
          Invocation.method(
            #savePostAndComments,
            [],
            {#post: post},
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Result<bool>>.value(_i6.dummyValue<_i4.Result<bool>>(
          this,
          Invocation.method(
            #savePostAndComments,
            [],
            {#post: post},
          ),
        )),
      ) as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<_i4.Result<bool>> deletePostAndComments({required int? postId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePostAndComments,
          [],
          {#postId: postId},
        ),
        returnValue:
            _i3.Future<_i4.Result<bool>>.value(_i6.dummyValue<_i4.Result<bool>>(
          this,
          Invocation.method(
            #deletePostAndComments,
            [],
            {#postId: postId},
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Result<bool>>.value(_i6.dummyValue<_i4.Result<bool>>(
          this,
          Invocation.method(
            #deletePostAndComments,
            [],
            {#postId: postId},
          ),
        )),
      ) as _i3.Future<_i4.Result<bool>>);
}
